"use strict";
import core from "@actions/core";
export const exportVariableImpl = core.exportVariable;
export const setSecretImpl = core.setSecret;
export const addPathImpl = core.addPath;
export const getInput1Impl = core.getInput;
export const getInput2Impl = core.getInput;
export const setOutputImpl = core.setOutput;
export const setCommandEchoImpl = core.setCommandEcho;
export const setFailedImpl = core.setFailed;
export const isDebugImpl = core.isDebug;
export const debugImpl = core.debug;
export const errorImpl = core.error;
export const warningImpl = core.warning;
export const infoImpl = core.info;
export const startGroupImpl = core.startGroup;
export const endGroupImpl = core.endGroup;
export const saveStateImpl = core.saveState;
export const getStateImpl = core.getState;
export const groupImpl = core.group;
