"use strict";
import core from "@actions/core";
export var exportVariableImpl = core.exportVariable;
export var setSecretImpl = core.setSecret;
export var addPathImpl = core.addPath;
export var getInput1Impl = core.getInput;
export var getInput2Impl = core.getInput;
export var setOutputImpl = core.setOutput;
export var setCommandEchoImpl = core.setCommandEcho;
export var setFailedImpl = core.setFailed;
export var isDebugImpl = core.isDebug;
export var debugImpl = core.debug;
export var errorImpl = core.error;
export var warningImpl = core.warning;
export var infoImpl = core.info;
export var startGroupImpl = core.startGroup;
export var endGroupImpl = core.endGroup;
export var saveStateImpl = core.saveState;
export var getStateImpl = core.getState;
export var groupImpl = core.group;
